const EMOJI_RULES = [
  { emoji: '🍎', keywords: ['mar', 'mere', 'apple', 'apples'] },
  { emoji: '🍐', keywords: ['para', 'pere', 'pear', 'pears'] },
  { emoji: '🍌', keywords: ['banana', 'banane'] },
  { emoji: '🍊', keywords: ['portocala', 'portocale', 'orange', 'oranges', 'mandarina', 'mandarine', 'clementina', 'clementine'] },
  { emoji: '🍋', keywords: ['lamaie', 'lamai', 'lemon', 'lemons', 'lime', 'lime-uri'] },
  { emoji: '🍉', keywords: ['pepene', 'watermelon', 'harbuz'] },
  { emoji: '🍈', keywords: ['pepene galben', 'melon', 'cantaloupe'] },
  { emoji: '🍍', keywords: ['ananas', 'pineapple'] },
  { emoji: '🥝', keywords: ['kiwi'] },
  { emoji: '🥭', keywords: ['mango'] },
  { emoji: '🍑', keywords: ['piersica', 'piersici', 'peach', 'peaches', 'nectarina', 'nectarine'] },
  { emoji: '🍒', keywords: ['cirese', 'cireasa', 'cherry', 'cherries', 'visine', 'sour cherry'] },
  { emoji: '🍑', keywords: ['caisa', 'caise', 'apricot', 'apricots', 'pruna', 'prune', 'plum', 'plums'] },
  { emoji: '🍓', keywords: ['capsuna', 'capsuni', 'strawberry', 'strawberries', 'fragi'] },
  { emoji: '🫐', keywords: ['afine', 'blueberry', 'blueberries', 'mure', 'blackberry', 'blackberries', 'coacaze', 'currants'] },
  { emoji: '🍇', keywords: ['struguri', 'grape', 'grapes'] },
  { emoji: '🥥', keywords: ['cocos', 'coconut'] },
  { emoji: '🍎', keywords: ['gutui', 'gutuie', 'quince', 'quinces'] },
  { emoji: '🥚', keywords: ['ou', 'oua', 'egg', 'eggs'] },
  { emoji: '🥛', keywords: ['lapte', 'milk'] },
  { emoji: '🥛', keywords: ['iaurt', 'yogurt', 'yoghurt', 'chefir', 'kefir', 'sana', 'lapte batut'] },
  { emoji: '🧈', keywords: ['smantana', 'sour cream', 'crema de gatit', 'cooking cream', 'frisca', 'whipping cream'] },
  { emoji: '🧀', keywords: ['branza', 'cascaval', 'telemea', 'cheese', 'mozzarella', 'parmesan', 'gouda', 'cheddar', 'emmental', 'feta', 'ricotta', 'burduf', 'brie', 'camembert'] },
  { emoji: '🧈', keywords: ['unt', 'butter', 'margarina', 'margarine'] },
  { emoji: '🍞', keywords: ['paine', 'bread', 'bagheta', 'baguette', 'toast', 'chifla', 'bun', 'covrig', 'lipie', 'tortilla', 'lavash'] },
  { emoji: '🥐', keywords: ['croissant', 'croisant', 'foietaj', 'puff pastry'] },
  { emoji: '🥨', keywords: ['pretzel', 'covrigei', 'sticks', 'grisine'] },
  { emoji: '🍪', keywords: ['biscuit', 'biscuiti', 'cookie', 'cookies', 'napolitane', 'wafer', 'wafers'] },
  { emoji: '🍰', keywords: ['prajitura', 'cake', 'tort', 'desert', 'dessert', 'ecler', 'savarina', 'cheesecake', 'brownie', 'muffin', 'briose'] },
  { emoji: '🍩', keywords: ['donut', 'donuts', 'gogosi', 'gogoasa'] },
  { emoji: '🍫', keywords: ['ciocolata', 'chocolate', 'cacao', 'nutella', 'crema de ciocolata'] },
  { emoji: '🍬', keywords: ['bomboane', 'candy', 'candies', 'jeleuri', 'jelly', 'lollipop'] },
  { emoji: '🍯', keywords: ['miere', 'honey', 'gem', 'dulceata', 'jam', 'marmalade', 'sirop', 'syrup'] },
  { emoji: '🍿', keywords: ['popcorn'] },
  { emoji: '🥜', keywords: ['alune', 'arahide', 'peanuts', 'nuci', 'nuts', 'caju', 'cashews', 'migdale', 'almonds', 'fistic', 'pistachio', 'seminte', 'seeds'] },
  { emoji: '🥓', keywords: ['bacon', 'slanina', 'kaiser', 'pancetta'] },
  { emoji: '🍗', keywords: ['pui', 'chicken', 'curcan', 'turkey', 'pulpe', 'piept de pui', 'piept de curcan', 'aripioare'] },
  { emoji: '🥩', keywords: ['vita', 'beef', 'porc', 'pork', 'miel', 'lamb', 'carne tocata', 'minced meat', 'cotlet', 'ceafa', 'muschi'] },
  { emoji: '🌭', keywords: ['carnati', 'sausage', 'sausages', 'crenvursti', 'hot dog'] },
  { emoji: '🍖', keywords: ['coaste', 'ribs', 'ciolan'] },
  { emoji: '🍔', keywords: ['burger', 'hamburger', 'meatballs', 'chiftele'] },
  { emoji: '🥪', keywords: ['sunca', 'ham', 'prosciutto', 'pastrama', 'mortadella', 'parizer', 'salam', 'sandwich'] },
  { emoji: '🐟', keywords: ['peste', 'fish', 'somon', 'salmon', 'ton', 'tuna', 'macrou', 'mackerel', 'pastrav', 'trout', 'sardine', 'hering', 'herring'] },
  { emoji: '🦐', keywords: ['creveti', 'shrimp', 'shrimp', 'prawns', 'fructe de mare', 'seafood', 'midii', 'mussels', 'calamari', 'squid', 'octopus'] },
  { emoji: '🍝', keywords: ['paste', 'pasta', 'spaghetti', 'penne', 'fusilli', 'tagliatelle', 'macaroane', 'noodles', 'lasagna'] },
  { emoji: '🍜', keywords: ['supa instant', 'instant noodles', 'ramen', 'pho', 'noodle soup'] },
  { emoji: '🍚', keywords: ['orez', 'rice', 'risotto'] },
  { emoji: '🫓', keywords: ['faina', 'flour', 'malai', 'cornmeal', 'gris', 'semolina', 'aluat', 'dough'] },
  { emoji: '🥣', keywords: ['cereale', 'cereal', 'oat', 'ovaz', 'fulgi', 'muesli', 'granola', 'terci', 'porridge'] },
  { emoji: '🥔', keywords: ['cartof', 'cartofi', 'potato', 'potatoes', 'piure', 'fries', 'french fries'] },
  { emoji: '🧅', keywords: ['ceapa', 'onion', 'onions', 'ceapa verde', 'green onion'] },
  { emoji: '🧄', keywords: ['usturoi', 'garlic'] },
  { emoji: '🥕', keywords: ['morcov', 'morcovi', 'carrot', 'carrots'] },
  { emoji: '🍅', keywords: ['rosie', 'rosii', 'tomato', 'tomatoes', 'bulion', 'passata'] },
  { emoji: '🥒', keywords: ['castravete', 'castraveti', 'cucumber', 'cucumbers', 'cornichon', 'muraturi'] },
  { emoji: '🥬', keywords: ['salata', 'lettuce', 'spanac', 'spinach', 'varza', 'cabbage', 'kale', 'rucola', 'arugula'] },
  { emoji: '🥦', keywords: ['broccoli', 'conopida', 'cauliflower'] },
  { emoji: '🌽', keywords: ['porumb', 'corn'] },
  { emoji: '🫘', keywords: ['fasole', 'beans', 'linte', 'lentils', 'naut', 'chickpeas', 'mazare', 'peas'] },
  { emoji: '🍄', keywords: ['ciuperci', 'ciuperca', 'mushroom', 'mushrooms'] },
  { emoji: '🫑', keywords: ['ardei', 'pepper', 'peppers', 'kapia', 'gogosar', 'chili'] },
  { emoji: '🥒', keywords: ['dovlecel', 'zucchini', 'zucchini', 'vinete', 'eggplant', 'aubergine'] },
  { emoji: '🥕', keywords: ['sfecla', 'beet', 'beets', 'ridiche', 'ridichi', 'radish', 'radishes'] },
  { emoji: '🍋', keywords: ['ghimbir', 'ginger', 'turmeric', 'curcuma'] },
  { emoji: '🥔', keywords: ['telina', 'celery root', 'pastarnac', 'parsnip'] },
  { emoji: '🥑', keywords: ['avocado'] },
  { emoji: '🫒', keywords: ['masline', 'olive', 'olives', 'ulei', 'oil', 'ulei de masline', 'olive oil'] },
  { emoji: '🍕', keywords: ['pizza', 'focaccia'] },
  { emoji: '🌮', keywords: ['taco', 'tacos', 'nachos', 'quesadilla'] },
  { emoji: '🥟', keywords: ['coltunasi', 'dumplings', 'pelmeni', 'gyoza', 'ravioli', 'tortellini'] },
  { emoji: '🍲', keywords: ['ciorba', 'soup', 'supa', 'stew', 'tocanita', 'tocana'] },
  { emoji: '🥫', keywords: ['conserva', 'conserve', 'canned', 'borcan', 'jar', 'pate', 'zacusca', 'fasole la conserva'] },
  { emoji: '🧂', keywords: ['sare', 'salt', 'condiment', 'condimente', 'spice', 'spices', 'piper', 'boia', 'oregano', 'busuioc', 'bazil', 'cimbru', 'thyme', 'curry'] },
  { emoji: '🧃', keywords: ['suc', 'juice', 'nectar', 'smoothie', 'limonada', 'lemonade'] },
  { emoji: '🥤', keywords: ['cola', 'fanta', 'sprite', 'soda', 'soft drink', 'pepsi', 'energizant', 'energy drink'] },
  { emoji: '💧', keywords: ['apa', 'water', 'mineral', 'sparkling water', 'still water'] },
  { emoji: '☕', keywords: ['cafea', 'coffee', 'espresso', 'cappuccino', 'latte'] },
  { emoji: '🍵', keywords: ['ceai', 'tea', 'matcha'] },
  { emoji: '🍺', keywords: ['bere', 'beer', 'lager', 'pilsner'] },
  { emoji: '🍷', keywords: ['vin', 'wine', 'rose', 'merlot', 'cabernet', 'sauvignon'] },
  { emoji: '🥂', keywords: ['prosecco', 'sampanie', 'champagne', 'cava'] },
  { emoji: '🍾', keywords: ['spumant', 'sparkling wine'] },
  { emoji: '🧻', keywords: ['hartie igienica', 'toilet paper', 'servetele', 'napkins', 'tissues', 'prosoape de hartie', 'paper towels'] },
  { emoji: '🧼', keywords: ['sapun', 'soap', 'gel de dus', 'body wash', 'dezinfectant', 'sanitizer'] },
  { emoji: '🧴', keywords: ['sampon', 'shampoo', 'detergent', 'balsam', 'conditioner', 'lotiune', 'lotion', 'crema', 'cream', 'deodorant'] },
  { emoji: '🪥', keywords: ['pasta de dinti', 'toothpaste', 'periuta', 'toothbrush', 'apa de gura', 'mouthwash'] },
  { emoji: '🧽', keywords: ['burete', 'bureti', 'sponge', 'sponges', 'laveta', 'cloth'] },
  { emoji: '🧺', keywords: ['detergent de rufe', 'balsam rufe', 'laundry detergent', 'fabric softener'] },
  { emoji: '🗑️', keywords: ['saci menajeri', 'garbage bags', 'trash bags', 'folie alimentara', 'baking paper', 'hartie de copt'] },
  { emoji: '🍼', keywords: ['formula', 'baby milk', 'lapte praf', 'scutece', 'diapers', 'servetele umede', 'baby wipes', 'piure bebe', 'baby food'] },
  { emoji: '🐶', keywords: ['hrana caini', 'dog food', 'caini', 'dog treats'] },
  { emoji: '🐱', keywords: ['hrana pisici', 'cat food', 'pisici', 'cat treats'] },
  { emoji: '🛍️', keywords: ['groceries', 'cumparaturi', 'shopping'] },
]

function normalizeText(value: string) {
  return value
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
}

export function getProductEmoji(productName: string, brand = '') {
  const haystack = normalizeText(`${productName} ${brand}`)

  for (const rule of EMOJI_RULES) {
    if (rule.keywords.some((keyword) => haystack.includes(keyword))) {
      return rule.emoji
    }
  }

  return '🛍️'
}
