// @vitest-environment happy-dom
//
// The three actions in the settings dialog that cannot be undone: rotating the
// invite code, leaving a household, and deleting one.
//
// They were the least covered part of the app and the least recoverable. The
// existing settings tests mount these panels but only assert which tabs appear,
// so nothing pinned the writes themselves — and the writes are where the damage
// is. Two properties in particular are invisible until they are wrong:
//
//   • A declined confirm must write NOTHING. The dialog is the only thing
//     between a mis-tap and a deleted household.
//   • Leaving filters on household_id AND user_id. RLS permits a member to
//     delete their own membership row; a delete that forgot the user_id filter
//     would ask the server to remove every membership in the household, and the
//     only thing refusing it would be a policy.
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'
import { mount, flushPromises } from '@vue/test-utils'
import DangerPanel from '../src/components/householdSettings/DangerPanel.vue'
import { createFakeDb } from './support/fakeSupabase.js'
import { isValidInviteCode } from '../src/lib/inviteCode'

const mocks = vi.hoisted(() => ({ db: null, userId: null }))

vi.mock('../src/supabase', () => ({
  useSupabase: () => mocks.db,
  getCatalogSupabase: () => null,
}))

vi.mock('@clerk/vue', async () => {
  const { ref } = await import('vue')
  mocks.userId = ref('u_me')
  return { useAuth: () => ({ userId: mocks.userId }) }
})

const wrappers = []

// `confirm` is handed down from the modal, which owns the one shared dialog.
// Here it is just a function returning an answer, which is the whole of the
// contract the panel depends on.
function mountPanel({ answer = true, ...props } = {}) {
  const confirm = vi.fn(async () => answer)
  const w = mount(DangerPanel, {
    props: {
      householdId: 'hh-1',
      householdName: 'Gorcea',
      isOwner: false,
      isOwnerOrModerator: true,
      confirm,
      ...props,
    },
  })
  wrappers.push(w)
  return { wrapper: w, confirm }
}

const writes = (table, op) => mocks.db.calls.filter((c) => c.table === table && c.op === op)

beforeEach(() => {
  mocks.db = createFakeDb()
  mocks.userId.value = 'u_me'
})

afterEach(() => {
  while (wrappers.length) wrappers.pop().unmount()
  vi.restoreAllMocks()
})

describe('rotating the invite code', () => {
  it('writes a fresh valid code and asks the view to refresh', async () => {
    mocks.db.handlers['households.update'] = () => ({ data: null, error: null })
    const { wrapper } = mountPanel()

    await wrapper.find('.panel-action-btn').trigger('click')
    await flushPromises()

    const updates = writes('households', 'update')
    expect(updates).toHaveLength(1)
    expect(updates[0].filters.id).toBe('hh-1')
    // Generated by lib/inviteCode, so the panel cannot invent a code the join
    // flow would then refuse.
    expect(isValidInviteCode(updates[0].payload.invite_code)).toBe(true)
    expect(wrapper.emitted('refresh-household')).toHaveLength(1)
  })

  it('writes nothing when the confirm is declined', async () => {
    const { wrapper, confirm } = mountPanel({ answer: false })

    await wrapper.find('.panel-action-btn').trigger('click')
    await flushPromises()

    expect(confirm).toHaveBeenCalled()
    expect(writes('households', 'update')).toHaveLength(0)
    expect(wrapper.emitted('refresh-household')).toBeUndefined()
  })

  it('surfaces a rejected write instead of reporting success', async () => {
    mocks.db.handlers['households.update'] = () => ({
      data: null,
      error: { code: '23505', message: 'duplicate key value' },
    })
    const { wrapper } = mountPanel()

    await wrapper.find('.panel-action-btn').trigger('click')
    await flushPromises()

    expect(wrapper.emitted('error')).toHaveLength(1)
    // The old code stopped the spinner and said nothing, which on screen reads
    // exactly like it worked.
    expect(wrapper.emitted('refresh-household')).toBeUndefined()
  })

  // Rotating the code invalidates every invite already handed out, so it is not
  // an ordinary member's to do.
  it('is not offered to a plain member', () => {
    const { wrapper } = mountPanel({ isOwnerOrModerator: false })
    expect(wrapper.find('.panel-action-btn').exists()).toBe(false)
  })
})

describe('leaving a household', () => {
  it('removes only the leaver, scoped to the one household', async () => {
    mocks.db.handlers['household_members.delete'] = () => ({ data: null, error: null })
    const { wrapper } = mountPanel({ isOwner: false })

    await wrapper.find('.danger-action-btn').trigger('click')
    await flushPromises()

    const deletes = writes('household_members', 'delete')
    expect(deletes).toHaveLength(1)
    // Both filters, and the second one is the load-bearing half.
    expect(deletes[0].filters).toEqual({ household_id: 'hh-1', user_id: 'u_me' })
    expect(wrapper.emitted('household-left')).toHaveLength(1)
  })

  it('writes nothing when the confirm is declined', async () => {
    const { wrapper } = mountPanel({ isOwner: false, answer: false })

    await wrapper.find('.danger-action-btn').trigger('click')
    await flushPromises()

    expect(writes('household_members', 'delete')).toHaveLength(0)
    expect(wrapper.emitted('household-left')).toBeUndefined()
  })

  it('reports a rejected leave rather than sending the view away', async () => {
    mocks.db.handlers['household_members.delete'] = () => ({
      data: null,
      error: { code: '42501', message: 'permission denied' },
    })
    const { wrapper } = mountPanel({ isOwner: false })

    await wrapper.find('.danger-action-btn').trigger('click')
    await flushPromises()

    expect(wrapper.emitted('error')).toHaveLength(1)
    // household-left sends HomeView off to another household. Emitting it after
    // a failed delete would move the user out of a household they are still in.
    expect(wrapper.emitted('household-left')).toBeUndefined()
  })

  // An owner cannot leave what they still own; they get Delete instead.
  it('is not offered to the owner', () => {
    const { wrapper } = mountPanel({ isOwner: true })
    expect(wrapper.find('.danger-action-btn--delete').exists()).toBe(true)
    expect(wrapper.findAll('.danger-action-btn')).toHaveLength(1)
  })
})

describe('deleting a household', () => {
  it('deletes the one household and tells the view to reconcile', async () => {
    mocks.db.handlers['households.delete'] = () => ({ data: null, error: null })
    const { wrapper } = mountPanel({ isOwner: true })

    await wrapper.find('.danger-action-btn--delete').trigger('click')
    await flushPromises()

    const deletes = writes('households', 'delete')
    expect(deletes).toHaveLength(1)
    expect(deletes[0].filters).toEqual({ id: 'hh-1' })
    expect(wrapper.emitted('household-deleted')).toHaveLength(1)
  })

  it('writes nothing when the confirm is declined', async () => {
    const { wrapper } = mountPanel({ isOwner: true, answer: false })

    await wrapper.find('.danger-action-btn--delete').trigger('click')
    await flushPromises()

    expect(writes('households', 'delete')).toHaveLength(0)
    expect(wrapper.emitted('household-deleted')).toBeUndefined()
  })

  it('reports a rejected delete rather than claiming the household is gone', async () => {
    mocks.db.handlers['households.delete'] = () => ({
      data: null,
      error: { code: '42501', message: 'permission denied' },
    })
    const { wrapper } = mountPanel({ isOwner: true })

    await wrapper.find('.danger-action-btn--delete').trigger('click')
    await flushPromises()

    expect(wrapper.emitted('error')).toHaveLength(1)
    expect(wrapper.emitted('household-deleted')).toBeUndefined()
  })

  it('is not offered to anyone but the owner', () => {
    const { wrapper } = mountPanel({ isOwner: false, isOwnerOrModerator: true })
    expect(wrapper.find('.danger-action-btn--delete').exists()).toBe(false)
  })
})
